name: CMake Build

on:
  push:
    branches:
      - master

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}\build
      
    - name: Generate Project Files
      working-directory: ${{runner.workspace}}\build
      run: cmake ${{runner.workspace}}

    - name: Build
      working-directory: ${{runner.workspace}}\build
      run: cmake --build . --config $BUILD_TYPE
